n<-c(2,3,5)
s<-c("aa","bb","Cc")
b<-c(T,F,F)
df<-data.frame(n,s,b)
mtcars
head(mtcars)
help(mtcars)

x<-rnorm(100)
y<-rnorm(100)
z<-sample(c("A","B","C"),size=100,replace=T,prob=c(.4,.3,.3))
df<-data.frame(x,y,z)
df
head(df)
colnames(df)<-c("col1","col2","name")
df$col1
head(df$col1)
hist(df$col1)
df[1:6,]
df[2,3]
df[1:6,1:2]
summary(df)
df[df$name=="A",1:3]
df[df$col1<0,1:2]
df$col1<0 & df$col2>0
x<-data.frame(col1=5,col2=7,name="Dave")
head(df)
df
df<-rbind(df,x)
df
crazy<-rnorm(101,11,2)
df<-cbind(df,crazy)
df
