auto<-read.csv("Auto.csv",na.strings="?")
head(auto)
attach(auto)
lmm_h<-lm(mpg~horsepower)
summary(lmm_h)
predict(lmm_h, data.frame(horsepower=(c(98))))
predict(lmm_h, data.frame(horsepower=(c(98))), interval = "confidence")
predict(lmm_h, data.frame(horsepower=(c(98))), interval = "prediction")
par(mfrow=c(2,2))
plot(lmm_h)
abline(lmm_h)
plot(horsepower,mpg)
abline(lmm_h,col="blue")

plot(auto, panel=panel.smooth)
pairs(auto)
plot(auto)
head(auto)
tmp<-auto[,c(-9)]
head(tmp)
auto2<-read.csv("Auto.csv",na.strings="?")
cor(auto2[,-9])
horsepower
fit<-lm(mpg~.-name,data=auto2)
summary(fit)
par(mfrow=c(2,2))
plot(fit)
fit<-lm(mpg~.+cylinders:displacement+displacement*horsepower+cylinders*horsepower-name+weight:year+weight:cylinders,data=auto2)
summary(fit)
fit<-lm(mpg~.+log(cylinders)+sqrt(displacement)+I(horsepower^2)-name,data=auto2)
summary(fit)
